Repository UCSD-E4E/smartfin-fw3, pull requests merged in 2025-04, with the labels that each got.

#187 fix: consolidated SleepTask::BootBehavior accesses to NVRAM accesses
  src/sleepTask.cpp
  src/sleepTask.hpp
Labels: enhancement

#213 29 doxygen output
  .github/workflows/build.yml
  Doxyfile
Labels: documentation

#211 docs: documentation for Task class
  src/task.hpp
Labels: documentation

#185 docs: updated fileCLI header docs
  src/fileCLI/fileCLI.hpp
Labels: documentation

#216 docs: added documentation for manufacturing test
  src/mfgTest/mfgTest.hpp
Labels: documentation

#199 docs: added docs for SystemDesc_ struct
  src/system.hpp
Labels: documentation

#222 209 deploy water sensor context window
  src/cellular/dataUpload.cpp
  src/chargeTask.cpp
  src/cli/cli.cpp
  src/product.hpp
  src/rideTask.cpp
  src/smartfin-fw3.ino
  src/system.cpp
  src/system.hpp
  src/vers.cpp
  src/watersensor/waterSensor.cpp
Labels: bug
